export const NCL_CLASSES = [
    { id: 1, label: "Classe 1: Produtos Químicos" },
    { id: 2, label: "Classe 2: Pinturas e Vernizes" },
    { id: 3, label: "Classe 3: Cosméticos e Limpeza" },
    { id: 4, label: "Classe 4: Óleos e Combustíveis" },
    { id: 5, label: "Classe 5: Farmacêuticos" },
    { id: 6, label: "Classe 6: Metais Comuns" },
    { id: 7, label: "Classe 7: Máquinas e Ferramentas" },
    { id: 8, label: "Classe 8: Ferramentas Manuais" },
    { id: 9, label: "Classe 9: Equipamentos Científicos e Softwares" },
    { id: 10, label: "Classe 10: Aparelhos Médicos" },
    { id: 11, label: "Classe 11: Iluminação e Aquecimento" },
    { id: 12, label: "Classe 12: Veículos" },
    { id: 13, label: "Classe 13: Armas de Fogo" },
    { id: 14, label: "Classe 14: Joias e Relógios" },
    { id: 15, label: "Classe 15: Instrumentos Musicais" },
    { id: 16, label: "Classe 16: Papelaria e Impressos" },
    { id: 17, label: "Classe 17: Borracha e Plásticos" },
    { id: 18, label: "Classe 18: Couro e Malas" },
    { id: 19, label: "Classe 19: Materiais de Construção (Não Metálicos)" },
    { id: 20, label: "Classe 20: Móveis" },
    { id: 21, label: "Classe 21: Utensílios Domésticos" },
    { id: 22, label: "Classe 22: Cordas e Velas" },
    { id: 23, label: "Classe 23: Fios Têxteis" },
    { id: 24, label: "Classe 24: Tecidos" },
    { id: 25, label: "Classe 25: Vestuário" },
    { id: 26, label: "Classe 26: Armarinho" },
    { id: 27, label: "Classe 27: Revestimentos de Piso" },
    { id: 28, label: "Classe 28: Brinquedos e Jogos" },
    { id: 29, label: "Classe 29: Alimentos (Carne, Peixe, Laticínios)" },
    { id: 30, label: "Classe 30: Alimentos (Café, Farinha, Doces)" },
    { id: 31, label: "Classe 31: Produtos Agrícolas" },
    { id: 32, label: "Classe 32: Bebidas (Não Alcoólicas)" },
    { id: 33, label: "Classe 33: Bebidas Alcoólicas" },
    { id: 34, label: "Classe 34: Tabaco" },
    { id: 35, label: "Classe 35: Publicidade e Gestão de Negócios" },
    { id: 36, label: "Classe 36: Seguros e Finanças" },
    { id: 37, label: "Classe 37: Construção e Reparo" },
    { id: 38, label: "Classe 38: Telecomunicações" },
    { id: 39, label: "Classe 39: Transporte e Viagens" },
    { id: 40, label: "Classe 40: Tratamento de Materiais" },
    { id: 41, label: "Classe 41: Educação e Entretenimento" },
    { id: 42, label: "Classe 42: Serviços Tecnológicos e Científicos" },
    { id: 43, label: "Classe 43: Serviços de Alimentação" },
    { id: 44, label: "Classe 44: Serviços Médicos e Veterinários" },
    { id: 45, label: "Classe 45: Serviços Jurídicos e Pessoais" },
];
